debug3
Co-Authored-By: SupunNarangoda <113084899+supunnarangoda@users.noreply.github.com>

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -26,6 +26,18 @@ jobs:
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-    - run: npm run getDependencies --if-present
-    - run: npm run start --if-present
+    - run: npm i express firebase firebase-tools firebase-admin bcrypt
+    - run: npm cache clean --force
+    - run: npm ci
+    - name: Start server
+      run: |
+        npm run start --if-present &
+        pid=$!
+        sleep 10 # Wait for the server to start (adjust the time as needed)
+        if ! ps -p $pid > /dev/null; then
+          echo "Server failed to start within the timeout period."
+          kill -9 $pid # Terminate the process if it hasn't started successfully
+          exit 1
+        fi
+      timeout-minutes: 5 # Set a timeout of 5 minutes for the start command
     - run: npm test
